import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CursorManager from "./components/CusorManager";
import AuthProvider from "./providers";
import { BubbleBackground } from "@/components/animate-ui/components/backgrounds/bubble";
import AuthVerifier from "./Auth/AuthVerifier";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BubbleBackground
          transition={{ stiffness: 100, damping: 20 }}
          interactive={true}
          className="h-screen w-screen -z-10 fixed"
        />
        <AuthProvider>
          <CursorManager />
          <AuthVerifier>{children}</AuthVerifier>
        </AuthProvider>
      </body>
    </html>
  );
}
